test:
  workers:
    number: 1
  rounds:
    - label: get a commodity.
      # 5000 transactions should create around 1000 cars per worker but not guaranteed
      # so need to set asset limits to less than 1000 for the other tests
      txNumber: 50
      rateControl:
        type: fixed-rate
        opts:
          tps: 5
      workload:
        module: benchmarks/basicSc/getCommodities.js
      config:
        timeout: 5
    #- label: Create an agreement.
            # 5000 transactions should create around 1000 cars per worker but not guaranteed
              # so need to set asset limits to less than 1000 for the other tests
      #txNumber: 50
      #rateControl:
        #type: fixed-load
        #opts:
          #transactionLoad: 5
      #workload:
        #module: benchmarks/basicSc/createAgreement.js