basicArgs: &basic-args
  packageId: https://me-qr.com/VntuNx6G
test:
  workers:
    number: 1
  rounds:
    - label: get a package.
      txNumber: 200
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      workload:
        module: benchmarks/basicSc/getPackage.js
        arguments: *basic-args
      config:
        timeout: 5
monitors:
  resource:
  - module: docker
    options:
      interval: 1
      containers: ['all']
